### PR TITLE
charterafrica app: Next.js Setup

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

This PR lays groundwork for the `charterafrica` app. It focus on setting up Next.js to include internationalization routing.

**NOTE**:

Special attention should be taken in testing/reviewing the building of Docker images. This PR shouldn't break that.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Screenshots

Peek 2022-10-13 11-09

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kelvinkipruto — APPROVED** [review]
Looks Good

**Review by esirK — APPROVED** [review]
LGTM.

I was able to run the app using `pnpm --filter charterafrica run dev` and also built the cfa site docker image successfully

**Comment by kilemensi** [comment]
> LGTM.
> 
> I was able to run the app using `pnpm --filter charterafrica run dev` and also built the cfa site docker image successfully

Cool, cool... I take it the you were also able to run the Docker image without any issues @esirK ?

**Comment by esirK** [comment]
> > LGTM.
> > I was able to run the app using `pnpm --filter charterafrica run dev` and also built the cfa site docker image successfully
> 
> Cool, cool... I take it the you were also able to run the Docker image without any issues @esirK ?

Yeah yeah. Just the 
`Error: @tryghost/content-api Config Missing: 'key' is required.`
which is expected since I don't have it set up.

**Pull request merged**
