### PR TITLE
Create Pesayetu dockerfile

### PR DESCRIPTION
**Pull request by kelvinkipruto**
## Description

This PR adds a `dockerfile` to deploy Pesayetu.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — APPROVED** [review]
🚀 

----

Add a story to limit the number of pages [built](https://github.com/CodeForAfrica/ui/blob/f16ec58440651b105999bf0de9753c07136ea655/apps/pesayetu/src/pages/explore/%5B%5B...slug%5D%5D.js#L50-L52) at build-time. Creating over 100 pages every time we build a new image is a waste of resources ... May be we should limit to building the main country page at build-time i.e. `/explore/ke`. The rest can be created the first-time they're accessed.

**Review by koechkevin — COMMENTED** [review]
@kelvinkipruto Where will this be deployed to? is it not dokku? if yes, why not add a workflow .

**Review by koechkevin — COMMENTED** [review]
@kelvinkipruto we can add
```const next = require("next");
const express = require("express");

const dev = process.env.NODE_ENV !== 'production';
const hostname = process.env.NEXT_HOSTNAME || "localhost";
const port = Number.parseInt(process.env.PORT || "3000", 10);

const app = next({ dev, hostname, port });
const nextHandler = app.getRequestHandler();

async function start() {
  await app.prepare();
  const server = express();
  server.get("*", (req, res) => nextHandler(req, res));
    server.post("*", (req, res) => nextHandler(req, res));
    server.put("*", (req, res) => nextHandler(req, res));
  const port = process.env.PORT || 3000;
  server.listen(port, async () => {
    console.log(`> Ready on http://localhost:${port}`);
  });
}

start();
```

**Comment by kilemensi** [comment]
I'm out of the @koechkevin, why do we need to add that?

**Comment by koechkevin** [comment]
> I'm out of the @koechkevin, why do we need to add that?

@kilemensi if we are to avoid using `pnpm start` or `next start`  serving production static files then we can use the [custom server](https://nextjs.org/docs/pages/building-your-application/configuring/custom-server) to start.

**Comment by kilemensi** [comment]
May be @koechkevin ... my main question is why or where does `pnpm` get the custom server to run but normal `npm` can not?

**Comment by koechkevin** [comment]
> May be @koechkevin ... my main question is why or where does `pnpm` get the custom server to run but normal `npm` can not?

@kilemensi `npm start` and `pnpm start`  work the same way here. Perhaps your proposal was to use `npm` instead of npm?

**Comment by kilemensi** [comment]
> > May be @koechkevin ... my main question is why or where does `pnpm` get the custom server to run but normal `npm` can not?
> 
> @kilemensi `npm start` and `pnpm start` work the same way here. Perhaps your proposal was to use `npm` instead of npm?

Sorry, no, I meant `node` @koechkevin ... why can't `node` find whatever `pnpm`/`npm` uses to start the app?

**Comment by koechkevin** [comment]
> > > May be @koechkevin ... my main question is why or where does `pnpm` get the custom server to run but normal `npm` can not?
> > 
> > 
> > @kilemensi `npm start` and `pnpm start` work the same way here. Perhaps your proposal was to use `npm` instead of npm?
> 
> Sorry, no, I meant `node` @koechkevin ... why can't `node` find whatever `pnpm`/`npm` uses to start the app?

I believe this is the [script](https://github.com/vercel/next.js/blob/v14.2.3/packages/next/src/cli/next-start.ts) executed by next start.

**Comment by kilemensi** [comment]
Please test the changes I've pushed @koechkevin

**Comment by kelvinkipruto** [comment]
@kilemensi Just tested this and it works like a charm. Thank you. @koechkevin Your review before we merge it.

**Review by koechkevin — APPROVED** [review]

**Pull request merged**
