### PR TITLE
charterafrica single post pages

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

This PR implements single post pages for news and research. It is implemented in a way that it can be extended to support events.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

S

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by kilemensi** [comment]
We need this deployed today @kelvinkipruto / @koechkevin

**Comment by kelvinkipruto** [comment]
@kilemensi, It looks like the post link is not being updated correctly. When I visit `/opportunities/news` and click on any of the news, it redirects to `/news/slug`, which results in a 404 error. However when I edit the url to `/opportunities/news/slug` it works as expected.

**Comment by kilemensi** [comment]
> @kilemensi, It looks like the post link is not being updated correctly. When I visit `/opportunities/news` and click on any of the news, it redirects to `/news/slug`, which results in a 404 error. However when I edit the url to `/opportunities/news/slug` it works as expected.

Just tested this @kelvinkipruto and everything works as expected. How's your CMS setup?

**Comment by kelvinkipruto** [comment]
> Just tested this @kelvinkipruto and everything works as expected. How's your CMS setup?

@kilemensi I have a single `news` collection. On the frontend, its `link` prop is `news/slug`
linkk
Perhaps its an issue with how I have set up my CMS. @koechkevin is it working on your end?

**Comment by kilemensi** [comment]
> > Just tested this @kelvinkipruto and everything works as expected. How's your CMS setup?
> 
> @kilemensi I have a single `news` collection....

Your CMS need updating @kelvinkipruto. You need to set `Knowledge` page as parent of `News` page in your CMS.

Screenshot 2023-03-02 at 16 46 00


See [dev](https://charterafrica.dev.codeforafrica.org/admin/collections/pages/63dcbbf266d29ba17b8421af) instance.

**Review by koechkevin — APPROVED** [review]

**Comment by kelvinkipruto** [comment]
@kilemensi Looks like the issue is with my CMS setup. Could you add me to the dev instance I check it out?

**Comment by kelvinkipruto** [comment]
Adding a parent solves the issue.

**Review by kelvinkipruto — APPROVED** [review]

**Pull request merged**
