### PR TITLE
[Chore] Add A11y checklist

### PR DESCRIPTION
**Pull request by gertie-sheshe**
## Description

This PR introduces a checklist to use to check that every feature and page we build is accessible. Before merging a PR, make sure to go through the list and ensure it is passing. These steps will not make the sites 100% accessible but it is a great step towards improving. The links provided on every checklist link to [18F Accessibility,](https://accessibility.18f.gov/) which is the US Government's Accessibility Guide to build products that all her people can access - and of course, to prevent suing

To show that we have been excluding disabled users, here are screenshots of PromiseTracker, PesaYetu and NBS sites when tested with WAVE tool. These are sites built for the public, which includes disabled users.

### PromiseTracker
Screenshot 2022-04-05 at 08 43 31
Screenshot 2022-04-05 at 08 43 57
Screenshot 2022-04-05 at 08 44 12

### PesaYetu
Screenshot 2022-04-05 at 08 47 45
Screenshot 2022-04-05 at 08 48 24

### Nigerian Bureau of Statistics
Screenshot 2022-04-05 at 08 50 14
Screenshot 2022-04-05 at 08 51 26

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
👍🏽 @gertie-sheshe .

I think you need first to introduce the concepts to the team so that they kind of know how to go about this i.e. how to fix a11y issues or even how to design with a11y in mind. But most importantly.

1. We're using MUI as foundation of our component system. How a11y ready is it? Does it pass the checklist you've included here?
2. Why should we adopt 18f.gov as our standard? e.g. who else is using it in general or Civic Tech space and/or is it better than other design systems such as [GOV.UK](https://design-system.service.gov.uk/accessibility/)?

**Comment by gertie-sheshe** [comment]
> 👍🏽 @gertie-sheshe .
> 
> I think you need first to introduce the concepts to the team so that they kind of know how to go about this i.e. how to fix a11y issues or even how to design with a11y in mind. But most importantly.
> 
> 1. We're using MUI as foundation of our component system. How a11y ready is it? Does it pass the checklist you've included here?
> 2. Why should we adopt 18f.gov as our standard? e.g. who else is using it in general or Civic Tech space and/or is it better than other design systems such as [GOV.UK](https://design-system.service.gov.uk/accessibility/)?

1. MUI does have Accessibility sections at the very bottom of most of its components + some of them come already with ARIA included. It is very Accessibility ready.
2. I used that because they have simplified wording for the issues listed on checklist. They eventually refer back to [WCAG ](https://www.w3.org/WAI/standards-guidelines/wcag/)(Web Content Accessibility Guidelines) which is the reference point globally. The wording can be quite complex there especially if you are starting out that's why I opted for 18F as a start. I am familiar with the GOV.UK one too as a reference point in a previous workplace, it points back to [WCAG ](https://www.w3.org/WAI/standards-guidelines/wcag/)too.

If we want independence we can go with[ A11yProject](https://www.a11yproject.com/checklist/) that was my second option.



I would be more than happy to champion introducing these concepts to the team 😊 @kilemensi

**Comment by kilemensi** [comment]
> > 👍🏽 @gertie-sheshe .
> > I think you need first to introduce the concepts to the team so that they kind of know how to go about this i.e. how to fix a11y issues or even how to design with a11y in mind. But most importantly.
> > 
> > 1. We're using MUI as foundation of our component system. How a11y ready is it? Does it pass the checklist you've included here?
> > 2. Why should we adopt 18f.gov as our standard? e.g. who else is using it in general or Civic Tech space and/or is it better than other design systems such as [GOV.UK](https://design-system.service.gov.uk/accessibility/)?
> 
>     1. MUI does have Accessibility sections at the very bottom of most of its components + some of them come already with ARIA included. It is very Accessibility ready.
> 
>     2. I used that because they have simplified wording for the issues listed on checklist. They eventually refer back to [WCAG ](https://www.w3.org/WAI/standards-guidelines/wcag/)(Web Content Accessibility Guidelines) which is the reference point globally. The wording can be quite complex there especially if you are starting out that's why I opted for 18F as a start. I am familiar with the GOV.UK one too as a reference point in a previous workplace, it points back to [WCAG ](https://www.w3.org/WAI/standards-guidelines/wcag/)too.
> 
> 
> If we want independence we can go with[ A11yProject](https://www.a11yproject.com/checklist/) that was my second option.
> 
> I would be more than happy to champion introducing these concepts to the team blush @kilemensi

Cool, cool @gertie-sheshe .

1. Then lets schedule a call for the intro as soon as possible,
2. To confirm, MUI components pass the checklist in this PR and any a11y issues will be of our own making.

**Review by kilemensi — COMMENTED** [review]
👍🏽  

---

I think [`eslint-plugin-jsx-a11y`](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules) covers most of these. We probably only need the WAVE check for now.

If there are ones that are not checked by eslint, then we can leave those here but the link should be to a publicly accessible site since this is an open-source project (and our TECH wiki isn't open to the public).

**Comment by kilemensi** [comment]
> 👍🏽
> 
> I think [`eslint-plugin-jsx-a11y`](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#supported-rules) covers most of these. We probably only need the WAVE check for now.
> 
> If there are ones that are not checked by eslint, then we can leave those here but the link should be to a publicly accessible site since this is an open-source project (and our TECH wiki isn't open to the public).

@gertie-sheshe ?

**Comment by kilemensi** [comment]
Lets rely on [eslint](https://github.com/CodeForAfrica/ui/pull/33#pullrequestreview-950037538) for now.

**Pull request closed without merging**
