### PR TITLE
Fix creating multiple pages failing

### LINKED ISSUE #473: BUG: Can't create multiple pages on a new database
**Describe the bug**
When running a clean installation of `charterafrica`, you can only create one page. Trying to create a second page fails with error:
```
{
    "errors": [
        {
            "name": "ValidationError",
            "message": "The following field is invalid: blocks.filterBar.sort.options.value",
            "data": [
                {
                    "message": "Value must be unique",
                    "field": "blocks.filterBar.sort.options.value"
                }
            ]
        }
    ]
}
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Switch to the main branch
2. Update the `MONGO_URL` environment variable to point to a clean database
3. Run `charterafrica` and log in to the admin
4. Try creating more than 1 page

**Expected behaviour**
You should be able to create more than 1 page.

### PR DESCRIPTION
**Pull request by kelvinkipruto**
## Description
This PR fixes a bug that prevents the creation of multiple pages in a new DB.

Fixes #473 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Why/How did `unique: true` prevent creating multiple pages @kelvinkipruto?

**Comment by kelvinkipruto** [comment]
@kilemensi According to the [docs](https://payloadcms.com/docs/fields/select), adding `unique` to `select` will:
> Enforce that each entry in the Collection has a unique value for this field.

I found removing this would fix the issue #473

**Comment by kelvinkipruto** [comment]
Not sure about it on your side, but can you reproduce issue #473?

**Comment by kilemensi** [comment]
> @kilemensi According to the [docs](https://payloadcms.com/docs/fields/select), adding `unique` to `select` will:
> 
> > Enforce that each entry in the Collection has a unique value for this field.
> 
> I found removing this would fix the issue #473

Yes but we don't even have that block in a new page @kelvinkipruto or am I misunderstanding the issue?

**Comment by kelvinkipruto** [comment]
@kilemensi Perhaps its an issue on my side alone, can you try and see if you get the same result as me for issue #473

**Comment by kelvinkipruto** [comment]
> Yes but we don't even have that block in a new page @kelvinkipruto or am I misunderstanding the issue?

@kilemensi Yes, even without adding any block to any page, it would just fail.

**Review by kilemensi — APPROVED** [review]
🚀

**Review by koechkevin — APPROVED** [review]

**Pull request merged**
