### PR TITLE
Introduce @hurumap/next/Map

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

This PR migrates `Map` component into `@hurumap/next` package. The main reason for moving to `next` instead of `core` package is because of it uses `next/dynamic` to dynamic load `leaflet` map client side.

### Aside

Not related to this PR but I seem to get `Error: Cycle detected in dataflow graph.` when running PesaYetu app locally. This has something to do with rendering Vega charts.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Screenshots

Screenshot 2024-07-31 at 15 45 05

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Lets do a very detailed review on this one @kelvinkipruto @koechkevin @m453h just to make sure the map does indeed work in all apps.

**Review by kelvinkipruto — APPROVED** [review]
Looks good @kilemensi. Tested it out on both `Pesayetu` and `ClimateMapped` and it works as expected.

**Comment by koechkevin** [comment]
Tested this and looks good, at least on `pesayetu` and `climatemappedafrica`. There are merge conflicts though

**Comment by kilemensi** [comment]
> Tested this and looks good, at least on `pesayetu` and `climatemappedafrica`. There are merge conflicts though

This is because you introduced `deepmerge` [dependency](https://github.com/CodeForAfrica/ui/blob/5032e98b98f1b9b2b6c80977f272ccda30bd55c9/packages/hurumap-core/package.json#L64) in `@hurumap/core` @koechkevin. Any reason you didn't use [`deepmerge`](https://github.com/CodeForAfrica/ui/blob/5032e98b98f1b9b2b6c80977f272ccda30bd55c9/packages/commons-ui-core/src/styles/createTheme/createTheme.js#L2) from `@mui/utils`?

**Comment by m453h** [comment]
@kilemensi  The map works as intended on `PesaYetu` and `ClimateMapped`.  However, I'm getting this warning when the map layers are rendered:  🤔

`Warning: useLayoutEffect does nothing on the server because its effect cannot be encoded into the server renderer's output form`

Seems it has to do with:
`ReactDOMServer.renderToStaticMarkup(
`

in `Map/Layers.js`

**Comment by kilemensi** [comment]
> @kilemensi The map ...
>

We're using `next/dynamic` so Map is never rendered on the server @m453h i.e. that warning shouldn't be applicable in our case.

... but I'll add this to my TODO to check why `useLayoutEffect` was used and if there're alternatives.

**Comment by koechkevin** [comment]
> > Tested this and looks good, at least on `pesayetu` and `climatemappedafrica`. There are merge conflicts though
> 
> This is because you introduced `deepmerge` [dependency](https://github.com/CodeForAfrica/ui/blob/5032e98b98f1b9b2b6c80977f272ccda30bd55c9/packages/hurumap-core/package.json#L64) in `@hurumap/core` @koechkevin. Any reason why you didn't use [`deepmerge`](https://github.com/CodeForAfrica/ui/blob/5032e98b98f1b9b2b6c80977f272ccda30bd55c9/packages/commons-ui-core/src/styles/createTheme/createTheme.js#L2) from `@mui/utils`?

I thought deepmerge from `@mui/utils` is specifically tailored for use with Material-UI, focusing on theme and style merging but looking at its code I think we can use it here as well.

**Comment by kilemensi** [comment]
> I thought deepmerge from `@mui/utils` ...
>

Cool, I've made the switch @koechkevin. Please test to make sure it hasn't broken the Bar charts in any way.

**Comment by kilemensi** [comment]
> ... but looking at its code I think we can use it here as well.
>

`@mui/utils/deepmerge` doesn't support merging arrays and hence can't be used in Scope. Added this to package README for future reference.

**Comment by koechkevin** [comment]
> > ... but looking at its code I think we can use it here as well.
> 
> >
> 
> 
> 
> `@mui/utils/deepmerge` doesn't support merging arrays and hence can't be used in Scope. Added this to package README for future reference.
> 
> 

Yeah, was just testing and I stumbled on an error

**Pull request merged**
