### PR TITLE
@charterafrica Community page

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

This PR implements /opportunities/community page per designs.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

S1

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by koechkevin — COMMENTED** [review]
Looks good to me.

Just a small one.

When you add more than one community platforms, text is overlapped.
Screenshot 2023-02-22 at 12 02 02

**Comment by kilemensi** [comment]
> Looks good to me.
> 
> Just a small one.
> 
> When you add more than one community platforms, text is overlapped. Screenshot 2023-02-22 at 12 02 02

The current design dimensions (especially width) only works up to the maximum of 3 items @koechkevin.

Unfortunately, relationship field doesn't support max config similar to array field. Our options appear to be:

i. Custom validation in the back-end to limit only up to 3,
ii. slice up to 3 items on the front-end regardless of how many items we receive from the back-end,
iii. New suggestion.

What are your thoughts?

**Comment by kelvinkipruto** [comment]
> iii. Fix number of columns to 3 but allow unlimited number of rows.

I think this is better @kilemensi @koechkevin

**Review by kelvinkipruto — COMMENTED** [review]
LGTM

**Comment by kilemensi** [comment]
If the number of cards isn't a multiple of 3 @kelvinkipruto / @koechkevin , there will be a bit of empty space left.

Screenshot 2023-02-22 at 13-01-06 Community charter AFRICA

**Review by koechkevin — APPROVED** [review]

**Pull request merged**
