### PR TITLE
Fix `NewsAndStories` regression

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

#241 (I think) introduced a small bug on the `NewsAndStories` component on the homepage. This PR addresses that.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

S

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by esirK** [comment]
Still looks kinda off for me @kilemensi 


Screenshot 2022-09-02 at 13 14 39

**Review by kelvinkipruto — APPROVED** [review]
LGTM

**Comment by kilemensi** [comment]
> Still looks kinda off for me @kilemensi
> 

Which screensize @esirK ?

**Comment by esirK** [comment]
> > Still looks kinda off for me @kilemensi
> 
> Which screensize @esirK ?

I've confirmed the change happens when I get to `1440`

**Review by esirK — APPROVED** [review]
LGTM

**Pull request merged**
