### PR TITLE
update app.json

### PR DESCRIPTION
**Pull request by koechkevin**
## Description

Not sure if this fixes the connection issue but updates  app.json as per https://code4africa.slack.com/archives/G0DNN0CN5/p1689237066105539?thread_ts=1689230348.614189&cid=G0DNN0CN5

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Can I assume you've tested this locally @koechkevin ?

**Comment by koechkevin** [comment]
> Can I assume you've tested this locally @koechkevin ?

Couldn't test this locally @kilemensi I had issues with my setup.

**Comment by kilemensi** [comment]
> > Can I assume you've tested this locally @koechkevin ?
> 
> Couldn't test this locally @kilemensi I had issues with my setup.

What issues, etc. @koechkevin? Did you reach out to @thepsalmist?

**Comment by kilemensi** [comment]
Cool @koechkevin , I'll wait for @thepsalmist  review then.

Having said that, it's important for you to develop necessary skills to deploy and debug deployment (since we have automated everything with GitHub Actions).

**Pull request merged**
