### PR TITLE
Fix @/climatemappedafrica HURUmap data handling

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

- [x] Load HURUmap profile only when HURUmap is enabled
- [x] Include HURUmap related blocks when HURUmap is enabled
- [x] Ensure data loading functions use similar arguments

**PENDING**
@koechkevin what should happen to the site Hero when HURUmap is disabled? Handle it in a separate PR.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore

## Screenshots

N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by koechkevin** [comment]
> @koechkevin what should happen to the site Hero when HURUmap is disabled? Handle it in a separate PR.

@kilemensi [this PR](https://github.com/CodeForAfrica/ui/pull/988) will fix that.

**Comment by kilemensi** [comment]
> @kilemensi [this PR](https://github.com/CodeForAfrica/ui/pull/988) will fix that.
>

Cool @koechkevin. Fix it how?

**Comment by kilemensi** [comment]
> @kilemensi Hero component only needs explore page slug to naavigate to when you click a location on the HeroMap. So we do not trigger `router.push` if explorePageSlug is null.
>

Cool, cool @koechkevin ... then don't do the hover styling as well i.e. don't give the user the indication that something is clickable when it isn't.

**Review by kelvinkipruto — APPROVED** [review]
LGTM

**Comment by kilemensi** [comment]
If all is good @kelvinkipruto / @koechkevin, please merge and deploy (I'll be stuck in meetings for the next 3 hours).

**Comment by koechkevin** [comment]
LGTM, I expect this to fail `Push to DOKKU` step only

**Pull request merged**
