### PR TITLE
[Chore] Apps Setup

### LINKED ISSUE #11: @promisetracker

### LINKED ISSUE #12: [Chore] Project Setup
Add / update the usual suspects to give us a good dev UX:

 - [x] Gitignore
 - [x] Editorconfig
 - [x] Prettier
 - [x] Eslint
 - [x] Lintstaged & Husky
 - [x] Changesets
 - [ ] ?

-----

Depends on: #6

### LINKED ISSUE #15: @pesayetu

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Setup PromiseTracker and PesaYetu apps as well as ensuring linting and testing work together in packages as well as apps.

Resolves #11, resolves #15, resolves #12 

Requires #19, requires #23 

## Type of change

- [x] Chore

## Screenshots

N/A

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nerdlet — APPROVED** [review]
@kilemensi Looks good 👍🏽  Separating jest from the config to have its own setup is 👌🏽

**Review by KhadijaMahanga — APPROVED** [review]
@kilemensi  Looks good. How about config for each of the project? Is it not part of setup?

**Review by gertie-sheshe — COMMENTED** [review]
Are we going to have a storybook setup? @kilemensi

**Comment by kilemensi** [comment]
> Are we going to have a storybook setup? @kilemensi

 Not in apps @gertie-sheshe. Just testing (Jest & Playwright).

**Review by nerdlet — APPROVED** [review]
@kilemensi 🚀 🚀

**Pull request merged**
