### PR TITLE
feature/roboshield-ui

### PR DESCRIPTION
**Pull request by m453h**
## Description
This PR fixes issues on the RoboShield UI as explained below: 

### Footer
- [x] Apply a consistent font style for headings on the footer.
- [x] Improve subscribe to news letter button style, this removes confusion of whether it is a button or a link.

### Form wizard
- [x] Separate the Reset button from the rest of the buttons on the last step of the Form wizard, this reduces chances of accidentally pressing the button and erasing all the options selected by the user. 
- [x] Change the behaviour of the code button on the form wizard to allow user to skip to the last form step instead of showing a dialog box.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Desktop

Screenshot 2024-06-24 at 11

Screenshot 2024-06-24 at 13 46 43

Mobile
Screenshot 2024-06-24 at 13 58 50

Screenshot

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
👍🏽 @m453h

When I click the `View current code`, it doesn't update my current selection e.g.

1. Move to Step 3. Paths
2. Select 'WordPress' as your platform
3. Click View current code

It seems the code is updated only when `CONTINUE` is clicked?

**Comment by m453h** [comment]
> 👍🏽 @m453h
> 
> When I click the `View current code`, it doesn't update my current selection e.g.
> 
> 1. Move to Step 3. Paths
> 2. Select 'WordPress' as your platform
> 3. Click View current code
> 
> It seems the code is updated only when `CONTINUE` is clicked?

@kilemensi, yes this is the current default behaviour, let me find a proper way to persist the changes to the code when the `View Current Code` button is clicked

**Comment by m453h** [comment]
> > 👍🏽 @m453h
> > When I click the `View current code`, it doesn't update my current selection e.g.
> > 
> > 1. Move to Step 3. Paths
> > 2. Select 'WordPress' as your platform
> > 3. Click View current code
> > 
> > It seems the code is updated only when `CONTINUE` is clicked?
> 
> @kilemensi, yes this is the current default behaviour, let me find a proper way to persist the changes to the code when the `View Current Code` button is clicked

Resolved this issue

> > 👍🏽 @m453h
> > When I click the `View current code`, it doesn't update my current selection e.g.
> > 
> > 1. Move to Step 3. Paths
> > 2. Select 'WordPress' as your platform
> > 3. Click View current code
> > 
> > It seems the code is updated only when `CONTINUE` is clicked?
> 
> @kilemensi, yes this is the current default behaviour, let me find a proper way to persist the changes to the code when the `View Current Code` button is clicked

I believe this is now properly resolved as shown below: 

ezgif-1-dab92341b9

**Review by kilemensi — APPROVED** [review]
👍🏽 

---

1. We'd need to refactor this so that all state management is handled in one place/component (including generating robots at each state transition). This should eliminate the need of passing around `SkipToLastStep`, etc.
2. You forgot to update the footer in `apps/codeforafrica` as well to match the changes in this PR.

**Pull request merged**
