### PR TITLE
ft/pinned-documents

### LINKED ISSUE #462: Pining documents
We should introduce a new feature that allows pinning specific documents at the top of the document list when rendered. This feature will provide editors with the ability to designate certain documents as pinned in the CMS, ensuring they are displayed at the top of the document list always.

**Proposed Solution**
To implement this feature, the following steps can be taken:

1. CMS Enhancement:
Introduce a new field in the document block in the CMS that allows editors to enter the titles of the documents they wish to pin.
2. Fetching Documents:
When fetching documents from the API, we use the search endpoint with a query parameter that searches for the specified titles. For example:
`search.json?q=title:"Kenya Country Brochure Agoa Final"`
3. Rendering the Document List:
Sort the fetched documents in a way that places the pinned documents at the top of the list.
Display the pinned documents first, followed by the remaining documents in their default order.

### PR DESCRIPTION
**Pull request by kelvinkipruto**
## Description

This PR implements the ability to pin some documents at the top

Fixes #462 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots
image
image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by koechkevin — APPROVED** [review]

**Comment by kilemensi** [comment]
Is the UI design for this ready @kelvinkipruto?

**Comment by kelvinkipruto** [comment]
@kilemensi No update in Figma yet.

**Comment by kelvinkipruto** [comment]
@kilemensi Now Ready

**Review by koechkevin — APPROVED** [review]

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
