### PR TITLE
Fix tooltip style

### LINKED ISSUE #825: Fix Map tooltip
**Describe the bug**
The Map tooltip in HURUMap isn't styled correctly

**Expected behaviour**
Fix the tooltip to match initial implementation.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by koechkevin**
## Description

FIxes broken tooltip on hurumap

Fixes #825
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kelvinkipruto — COMMENTED** [review]
@koechkevin Testing it out, and it looks like the label is not correctly centred:
image

**Review by kelvinkipruto — APPROVED** [review]

**Review by m453h — COMMENTED** [review]
It looks good, I have just a small observation:

I think we need to add a bit of space between the `NameTypography` and `LevelTypography` and also to try to  center the  `LevelTypography` .

Im also trying out to see how feasible it is and might share my suggestion once I have something working.

tooltip

**Comment by koechkevin** [comment]
@m453h Please retest

**Review by m453h — APPROVED** [review]

**Comment by m453h** [comment]
> @m453h Please retest

Awesome, this looks perfect !

**Pull request merged**
