### PR TITLE
Feat @/charterafrica/cms Focal Countries support

### LINKED ISSUE #282: @/charterafrica/cms/FocalCountries Global
Using any of the [Fields](https://payloadcms.com/docs/fields/overview), create Focal Countries support in the **globals** section of the CMS i.e. same date will be shared between multiple pages. Replace the hard-coded focal-countries content on homepage with the CMS data.

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Fixes #282 .

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots

Screenshot 2023-01-13 at 17-15-45 Focal Countries - Payload

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by koechkevin — COMMENTED** [review]
image

@kilemensi , 

Code looks good, however I get the above error trying to test this branch out

**Comment by kilemensi** [comment]
> Code looks good, however I get the above error trying to test this branch out

Open the end point on your local Payload @koechkevin (e.g. http://localhost:3003/api/globals/focal-countries) and see if anything is returned as `undefined`. Everything should have values or `null`.

**Comment by koechkevin** [comment]
> > Code looks good, however I get the above error trying to test this branch out
> 
> Open the end point on your local Payload @koechkevin (e.g. http://localhost:3003/api/globals/focal-countries) and see if anything is returned as `undefined`. Everything should have values or `null`.

The object looks good.

Just wondering why the shape of `fc` object looks like this when I log on the console
image

**Comment by kilemensi** [comment]
> > > Code looks good, however I get the above error trying to test this branch out
> > 
> > 
> > Open the end point on your local Payload @koechkevin (e.g. http://localhost:3003/api/globals/focal-countries) and see if anything is returned as `undefined`. Everything should have values or `null`.
> 
> The object looks good.
> 
> Just wondering why the shape of `fc` object looks like this when I log on the console image

I'm forcing a null [here](https://github.com/CodeForAfrica/ui/pull/293/files#diff-850feb2d6b1350b30873fe896f6b323b5d7dcde1aae742324d9318e0f45853feR7-R10) @koechkevin so I hope that fixes it (when there is no data).

**Pull request merged**
