### PR TITLE
Add Dockerfile to be used for ui deployment

### PR DESCRIPTION
**Pull request by esirK**
## Description

Add Dockerfile to be used for ui deployment

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by esirK** [comment]
@kilemensi 
Instead of using the `contrib/dokku/Dockerfile` approach as we have done before, I thought having the specific dockerfile inside an individual app like a better approach. What do you think?

**Comment by kilemensi** [comment]
> @kilemensi Instead of using the `contrib/dokku/Dockerfile` approach as we have done before (For dokku deployment), I thought having the specific dockerfile inside an individual app like a better approach. What do you think?

My only reservations with this approach is: `Dockerfile` at the root of an app always feels like a file to **build** an image of the app. But this `Dockerfile` is for **pulling** an already built image of the said app.

**Comment by esirK** [comment]
> 

So placing it under `apps/codeforafrica/contrib/dokku/Dockerfile` would be a better approach @kilemensi ?

**Comment by kilemensi** [comment]
> > 
> 
> So placing it under `apps/codeforafrica/contrib/dokku/Dockerfile` ...

I think so @esirK ... since it clearly shows if you aren't using Dokku, you probably don't need it.

**Comment by esirK** [comment]
> I think so @esirK ... since it clearly shows if you aren't using Dokku, you probably don't need it.

All good now I think @kilemensi

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
