### PR TITLE
Add Africa to list of countries.

### PR DESCRIPTION
**Pull request by koechkevin**
## Description

As per discussion on [this item on Airtable](https://airtable.com/appIiCxqhhOYgB7RD/tblRrOB6JXLW0qbTP/viwKAgMm4aDxfPuuK/recN1JJJhHlpBzZ9K?blocks=hide), we need to add Africa as a list of countries.

Fixes # [issue](https://airtable.com/appIiCxqhhOYgB7RD/tblRrOB6JXLW0qbTP/viwKAgMm4aDxfPuuK/recN1JJJhHlpBzZ9K?blocks=hide)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Thanks @koechkevin 

I think there is a question from Eric that needs addressing:
> But HURIDOCs has no HQ in Africa. The only office is in Geneva. What's the criteria of having the HQ country set to Africa for this entry

If there is indeed the need to add continents, then lets rename `countries.json` (and variables/functions dealing with countries) to `locations.json` or something like that.

**Comment by koechkevin** [comment]
> Thanks @koechkevin 
> 
> 
> 
> I think there is a question from Eric that needs addressing:
> 
> > But HURIDOCs has no HQ in Africa. The only office is in Geneva. What's the criteria of having the HQ country set to Africa for this entry
> 
> 
> 
> If there is indeed the need to add continents, then lets rename `countries.json` (and variables/functions dealing with countries) to `locations.json` or something like that.

@kilemensi I think the concern by Eric was answered by Sarah on this comment.

```
@Kevin Koech yes please we'd need to add Africa as a country. In the meanwhile, this particular organisation is based in Switzerland

```

**Comment by kilemensi** [comment]
>In the meanwhile, this particular organisation is based in Switzerland

Does this mean we also be showing European countries in the drop downs @koechkevin ?

**Comment by koechkevin** [comment]
> > In the meanwhile, this particular organisation is based in Switzerland
> 
> Does this mean we also show European countries in the drop downs @koechkevin ?

@kilemensi there 2 fields
1. Operating Countries - Only African countries where the tool is operating from. This country is supposed to only be African countries. But a provision to add Africa as an option in this list was requested.
2. HQ Country - Any country in the world.

**Comment by koechkevin** [comment]
> How does the above look like on the site @koechkevin ?

@kilemensi Single tool page does not display operating countries but used during filters(See image below).

image

**Comment by kilemensi** [comment]
Thanks @koechkevin.

To make sure we're all on the same page, there are three pages that uses Location/Countries (well, four but I'm datasets page is not related to Airtable).

1. [Tools](https://charter.africa/resources/tools) page,
2. [Organisations](https://charter.africa/resources/organisations) page, and
3. [Contributors](https://charter.africa/resources/contributors) page.

My questions:
1. Do these pages use **operating** or _HQ_ country/location?
2. If operating, is it possible to have multiple operating countries e.g. a tool could be operating in Kenya and Uganda but not rest of Africa?

**Comment by koechkevin** [comment]
> Thanks @koechkevin.
> 
> To make sure we're all on the same page, there are three pages that uses Location/Countries (well, four but I'm datasets page is not related to Airtable).
> 
> 1. [Tools](https://charter.africa/resources/tools) page,
> 2. [Organisations](https://charter.africa/resources/organisations) page, and
> 3. [Contributors](https://charter.africa/resources/contributors) page.
> 
> My questions:
> 
> 1. Do these pages use **operating** or _HQ_ country/location?
> 2. If operating, is it possible to have multiple operating countries e.g. a tool could be operating in Kenya and Uganda but not rest of Africa?

@kilemensi 
1. Organisations & Contributors use location. Tools use operating.
2. Yes, [this](https://airtable.com/appIiCxqhhOYgB7RD/tblRrOB6JXLW0qbTP/viwKAgMm4aDxfPuuK/rec5veIxzmBnK26Dc?blocks=hide) is such example.

**Comment by kilemensi** [comment]
Cool, cool... @koechkevin . So the drop-downs in Organisations and Contributors pages will **not** show `Africa`, correct?

**Comment by koechkevin** [comment]
> Cool, cool... @koechkevin . So the drop-downs in Organisations and Contributors pages will **not** show `Africa`, correct?

At the moment we are using the same list, so Africa still shows up

**Comment by kilemensi** [comment]
From your description @koechkevin , this shouldn't be happening. Since it's our own predefined list, can't we define countries and locations separately? For example:
```js
const countries = [
  {
    name: "Afghanistan",
    label: {
      pt: "Afeganistão",
      en: "Afghanistan",
      fr: "Afghanistan",
    },
    value: "Afghanistan",
    continent: "Asia",
  },
  ....
];

const regions = [
  {
    name: "Africa",
    label: {
      pt: "África",
      en: "Africa",
      fr: "Afrique",
    },
    value: "Africa",
    continent: "Africa",
  },
  ....
];

const locations = [...countries, ...regions]

const toOptions = ({ label, value }) => ({ label, value }); 

export const allCountries = countries.map(toOptions);

export const allLocations = locations.map(toOptions);
```

**Review by kilemensi — APPROVED** [review]

**Pull request merged**
