### PR TITLE
Patners social media connection

### LINKED ISSUE #213: Fix connect on partner pages
As a follow up to https://github.com/CodeForAfrica/ui/pull/191, fix **Connect** social media links on partners pages.

### PR DESCRIPTION
**Pull request by kelvinkipruto**
## Description
Social Media Connect for Partners

Fixes #213 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by esirK — CHANGES_REQUESTED** [review]
Looks alright @kelvinkipruto .
Could you add screenshots for the added functionality?
Also, seems like only `unesco` partner was updated instead of all Partners.

**Comment by kelvinkipruto** [comment]
I only added links for unesco. Let me go ahead and add the rest.

**Review by kilemensi — COMMENTED** [review]
👍🏽 . There is merge conflict.

**Review by kelvinkipruto — COMMENTED** [review]
Fixed

**Review by kilemensi — APPROVED** [review]
🚀

**Review by esirK — APPROVED** [review]

**Pull request merged**
