### PR TITLE
[Chore] Scripts Folder

### PR DESCRIPTION
**Pull request by gertie-sheshe**
## Description

This adds a folder that houses most of the scripts i.e `lint` `test` `clean` as they seem to be the same commands repeated over the packages

## Running

Make sure to run `chmod -R +x scripts` on root folder first before running any command

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
👍🏽 @gertie-sheshe 


____________

Still on mobile so can’t test this:

1. packages run Jest only when testing but apps will run Jest and Playwright. How would we handle such situations where individual packages/apps need to make slight adjustments to commands?

2. Can turborepo still run things in parallel ie does scripty play nice with Turborepo?

**Comment by gertie-sheshe** [comment]
> 👍🏽 @gertie-sheshe
> 
> Still on mobile so can’t test this:
> 
> 1. packages run Jest only when testing but apps will run Jest and Playwright. How would we handle such situations where individual packages/apps need to make slight adjustments to commands?
> 2. Can turborepo still run things in parallel ie does scripty play nice with Turborepo?

1. If the command for apps is the same then we can move the `test` command to a different folder e.g `apps`
2. So far so good, but let me dig further into that tomorrow morning in case I have missed any gotchas

**Comment by KhadijaMahanga** [comment]
@gertie-sheshe this PR has conflicts

**Comment by kilemensi** [comment]
Think need to revisit this discussion on a later stage.

**Pull request closed without merging**
